spring:
  jpa:
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         id:
          new_generator_mappings: false

#maximum number of milliseconds that a client will wait for a connection
  datasource:
    hikari:
      connection-timeout: 20000 
#minimum number of idle connections maintained by HikariCP in a connection pool
      minimum-idle: 1 
#maximum pool size
      maximum-pool-size: 10
#maximum idle time for connection 
      idle-timeout: 300000 
# maximum lifetime in milliseconds of a connection in the pool after it is closed.
      max-lifetime: 600000
#default auto-commit behavior. 
      auto-commit: true 

driver:
  geo:
    location:
      scheduler:
        enabled: true
        fixed:
          delay: 3000
        initial:
          delay: 10000
  notvalid:
    geo:
      location:
        scheduler:
          enabled: true
          fixed:
            delay: 60000
          initial:
            delay: 10000

management:
  endpoint:
    health:
      show-details: ALWAYS
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: shutdown


hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  default_schema: public
entitymanager:
  packagesToScan: com.triesten.eld.domain
---
spring:
   profiles: local
   datasource:
      url: jdbc:postgresql://78.46.69.89:10691/dev_simpletruckeld
      username: postgres
      password: "{cipher}AQB7sjTQ3KYT0Wjlf9qqAXnrcElFCK2UydluuZMZxYeBMeBmSe1Dmp+njDkWC1t8bar5PVsYUo8v5yU+/DDWEn4WcuTJXlG52XuORqVE7OG1hiO/xLdXworih2kHusI692KVrZZWp8YNbdG0+Wiw8XDl/IKA88l24TBDgzHcE7sBERMlA7lerYiMqNTVJwbUSC5y+iEHjpEp3k/XGkuIHX1asr5f374wpAnIPAoUbjWU1L5NrfT1ZxXU2belUTpSaZpALu/fMgbz3Cd1vW7+PNv0JPNvYP/JsB0Uz08b3NnLcIs38FGji71itXET3UFhqOpYm/3gdOmVvm5T6LWe+loLmhNOjJvQMwiMoccMrWgge12dUbRhy4cko+Jp7Qf7ECU="


hibernate:
  show_sql: false
logging:
  level:
    com:
      triesten:
        eld: DEBUG
    org: 
      hibernate:
        SQL: DEBUG
      springframework:
        jdbc:
          core: DEBUG

